[colors]
# Regular colors
background = '#16181a'
black = '#1e2124'
blue = '#78a8e8'
cursor = '#ffffff'
cyan = '#7ed8e8'
foreground  = '#ffffff'
green = '#7ee088'
magenta = '#b07ee8'
red = '#e8796f'
white = '#ffffff'
yellow = '#e3c875'

# UI colors
tabs = '#3c4048'
tabs-active = '#7b8496'
selection-foreground = '#ffffff'
selection-background = '#1e2124'

# Dim colors
dim-black = '#1c1f22'
dim-blue = '#648bbe'
dim-cyan = '#69b1be'
dim-foreground  = '#d0d0d1'
dim-green = '#69b872'
dim-magenta = '#be64b2'
dim-red = '#be655e'
dim-white = '#d0d0d1'
dim-yellow = '#baa462'

# Light colors
light-black = '#4a4d4f'
light-blue = '#93b9ec'
light-cyan = '#97dfec'
light-foreground  = '#ffffff'
light-green = '#97e69f'
light-magenta = '#ec93df'
light-red = '#ec938b'
light-white = '#ffffff'
light-yellow = '#e8d390'
