[colors]
# Regular colors
background = '#ffffff'
black = '#eaeaea'
blue = '#0057d1'
cursor = '#16181a'
cyan = '#008c99'
foreground  = '#16181a'
green = '#008b0c'
magenta = '#d100bf'
red = '#d11500'
white = '#16181a'
yellow = '#997b00'

# UI colors
tabs = '#acacac'
tabs-active = '#7b8496'
selection-foreground = '#16181a'
selection-background = '#eaeaea'

# Dim colors
dim-black = '#bfc0c0'
dim-blue = '#044aac'
dim-cyan = '#04747f'
dim-foreground  = '#16181a'
dim-green = '#04740e'
dim-magenta = '#ab049e'
dim-red = '#ab1505'
dim-white = '#16181a'
dim-yellow = '#7e6705'

# Light colors
light-black = '#eeeeee'
light-blue = '#3278da'
light-cyan = '#32a3ad'
light-foreground  = '#444647'
light-green = '#32a23c'
light-magenta = '#da32cb'
light-red = '#da4332'
light-white = '#444647'
light-yellow = '#ad9532'
