# cyberdream theme for alacritty
[[colors.indexed_colors]]
color = "0xe3a875"
index = 16

[[colors.indexed_colors]]
color = "0xe8796f"
index = 17

[colors.bright]
black = "0x3c4048"
blue = "0x78a8e8"
cyan = "0x7ed8e8"
green = "0x7ee088"
magenta = "0xb07ee8"
red = "0xe8796f"
white = "0xffffff"
yellow = "0xe3c875"

[colors.normal]
black = "0x16181a"
blue = "0x78a8e8"
cyan = "0x7ed8e8"
green = "0x7ee088"
magenta = "0xb07ee8"
red = "0xe8796f"
white = "0xffffff"
yellow = "0xe3c875"

[colors.primary]
background = "0x16181a"
foreground = "0xffffff"

[colors.selection]
background = "0x3c4048"
foreground = "0xffffff"
