# Cyberdream theme for foot terminal
[cursor]
color=      2b2c2e e5e5e5

[colors]
background= 2b2c2e
foreground= e5e5e5
# The  eight basic ANSI colors (Black, Red, Green, Yellow, Blue, Magenta, Cyan, White)
regular0=   2b2c2e
regular1=   e57164
regular2=   64e570
regular3=   dae564
regular4=   649ae5
regular5=   b064e5
regular6=   64dae5
regular7=   e5e5e5
# The eight bright ANSI colors (Black, Red, Green, Yellow, Blue, Magenta, Cyan, White)
bright0=    494c53
bright1=    e57164
bright2=    64e570
bright3=    dae564
bright4=    649ae5
bright5=    b064e5
bright6=    64dae5
bright7=    e5e5e5
bright7=    e5e5e5
