# Cyberdream theme for foot terminal
[cursor]
color=      16181a ffffff

[colors]
background= 16181a
foreground= ffffff
# The  eight basic ANSI colors (Black, Red, Green, Yellow, Blue, Magenta, Cyan, White)
regular0=   16181a
regular1=   e8796f
regular2=   7ee088
regular3=   e3c875
regular4=   78a8e8
regular5=   b07ee8
regular6=   7ed8e8
regular7=   ffffff
# The eight bright ANSI colors (Black, Red, Green, Yellow, Blue, Magenta, Cyan, White)
bright0=    3c4048
bright1=    e8796f
bright2=    7ee088
bright3=    e3c875
bright4=    78a8e8
bright5=    b07ee8
bright6=    7ed8e8
bright7=    ffffff
bright7=    ffffff
