# Cyberdream theme for foot terminal
[cursor]
color=      282c34 d7dae0

[colors]
background= 282c34
foreground= d7dae0
# The  eight basic ANSI colors (Black, Red, Green, Yellow, Blue, Magenta, Cyan, White)
regular0=   282c34
regular1=   e06c75
regular2=   98c379
regular3=   e5c07b
regular4=   61afef
regular5=   c678dd
regular6=   56b6c2
regular7=   d7dae0
# The eight bright ANSI colors (Black, Red, Green, Yellow, Blue, Magenta, Cyan, White)
bright0=    3e4451
bright1=    e06c75
bright2=    98c379
bright3=    e5c07b
bright4=    61afef
bright5=    c678dd
bright6=    56b6c2
bright7=    d7dae0
bright7=    d7dae0
