# --> Catppuccin (Cyberdream)
set -ogq @thm_bg "#2b2c2e"
set -ogq @thm_fg "#e5e5e5"

# Colors
set -ogq @thm_rosewater "#e56499"
set -ogq @thm_flamingo "#e56499"
set -ogq @thm_pink "#e56499"
set -ogq @thm_mauve "#e564da"
set -ogq @thm_red "#e57164"
set -ogq @thm_maroon "#e5b064"
set -ogq @thm_peach "#e5b064"
set -ogq @thm_yellow "#dae564"
set -ogq @thm_green "#64e570"
set -ogq @thm_teal "#64dae5"
set -ogq @thm_sky "#64dae5"
set -ogq @thm_sapphire "#64dae5"
set -ogq @thm_blue "#649ae5"
set -ogq @thm_lavender "#b064e5"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#7c8391"
set -ogq @thm_subtext_0 "#7c8391"
set -ogq @thm_overlay_2 "#494c53"
set -ogq @thm_overlay_1 "#494c53"
set -ogq @thm_overlay_0 "#494c53"
set -ogq @thm_surface_2 "#313436"
set -ogq @thm_surface_1 "#313436"
set -ogq @thm_surface_0 "#313436"
set -ogq @thm_mantle "#313436"
set -ogq @thm_crust "#313436"
