# --> Catppuccin (Cyberdream)
set -ogq @thm_bg "#16181a"
set -ogq @thm_fg "#ffffff"

# Colors
set -ogq @thm_rosewater "#e878a8"
set -ogq @thm_flamingo "#e878a8"
set -ogq @thm_pink "#e878a8"
set -ogq @thm_mauve "#e878d8"
set -ogq @thm_red "#e8796f"
set -ogq @thm_maroon "#e3a875"
set -ogq @thm_peach "#e3a875"
set -ogq @thm_yellow "#e3c875"
set -ogq @thm_green "#7ee088"
set -ogq @thm_teal "#7ed8e8"
set -ogq @thm_sky "#7ed8e8"
set -ogq @thm_sapphire "#7ed8e8"
set -ogq @thm_blue "#78a8e8"
set -ogq @thm_lavender "#b07ee8"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#7b8496"
set -ogq @thm_subtext_0 "#7b8496"
set -ogq @thm_overlay_2 "#3c4048"
set -ogq @thm_overlay_1 "#3c4048"
set -ogq @thm_overlay_0 "#3c4048"
set -ogq @thm_surface_2 "#1e2124"
set -ogq @thm_surface_1 "#1e2124"
set -ogq @thm_surface_0 "#1e2124"
set -ogq @thm_mantle "#1e2124"
set -ogq @thm_crust "#1e2124"
