# Borders
file_panel_border = "#484e58"
sidebar_border = "#484e58"
footer_border = "#484e58"

file_panel_border_active = "#eea0c2"
sidebar_border_active = "#e3a875"
footer_border_active = "#e878d8"
modal_border_active = "#eea0c2"

full_screen_bg = "#16181a"
file_panel_bg = "#16181a"
sidebar_bg = "#16181a"
footer_bg = "#16181a"
modal_bg = "#16181a"

full_screen_fg = "#d7dadf"
file_panel_fg = "#d7dadf"
sidebar_fg = "#ffffff"
footer_fg = "#d7dadf"
modal_fg = "#d7dadf"

cursor = "#ffffff"
correct = "#7ee088"
error = "#e8796f"
hint = "#78a8e8"
cancel = "#e3c875"
# Gradient color can only have two colors!
gradient_color = ["#78a8e8", "#b07ee8"]

file_panel_top_directory_icon = "#7ed8e8"
file_panel_top_path = "#78a8e8"
file_panel_item_selected_fg = "#e3a875"
file_panel_item_selected_bg = ""

sidebar_title = "#e3a875"
sidebar_item_selected_fg = "#7ee088"
sidebar_item_selected_bg = ""
sidebar_divider = "#1e2124"

modal_cancel_fg = "#3c4048"
modal_cancel_bg = "#e8796f"

modal_confirm_fg = "#3c4048"
modal_confirm_bg = "#7ee088"

help_menu_hotkey = "#7ed8e8"
help_menu_title = "#b07ee8"
