# cyberdream theme for kitty
background            #282c34
foreground            #d7dae0
cursor                #d7dae0
cursor_text_color     #282c34
selection_background  #3e4451
color0                #282c34
color8                #3e4451
color1                #e06c75
color9                #e06c75
color2                #98c379
color10               #98c379
color3                #e5c07b
color11               #e5c07b
color4                #61afef
color12               #61afef
color5                #c678dd
color13               #c678dd
color6                #56b6c2
color14               #56b6c2
color7                #d7dae0
color15               #d7dae0
selection_foreground  #d7dae0
active_tab_foreground #000000
active_tab_background #d19a66
inactive_tab_foreground #d7dae0
inactive_tab_background #282c34
