# cyberdream theme for kitty
background            #2b2c2e
foreground            #e5e5e5
cursor                #e5e5e5
cursor_text_color     #2b2c2e
selection_background  #494c53
color0                #2b2c2e
color8                #494c53
color1                #e57164
color9                #e57164
color2                #64e570
color10               #64e570
color3                #dae564
color11               #dae564
color4                #649ae5
color12               #649ae5
color5                #b064e5
color13               #b064e5
color6                #64dae5
color14               #64dae5
color7                #e5e5e5
color15               #e5e5e5
selection_foreground  #e5e5e5
active_tab_foreground #000000
active_tab_background #e5b064
inactive_tab_foreground #e5e5e5
inactive_tab_background #2b2c2e
